<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Craftsvilla" duration-ms="44404" started-at="2018-11-13T02:51:43Z" finished-at="2018-11-13T02:52:27Z">
    <groups>
    </groups>
    <test name="Regression" duration-ms="44404" started-at="2018-11-13T02:51:43Z" finished-at="2018-11-13T02:52:27Z">
      <class name="com.craftsvilla.testscripts.EmbroidedSareesScripts">
        <test-method status="PASS" signature="OpenApp(java.lang.String)[pri:0, instance:com.craftsvilla.testscripts.EmbroidedSareesScripts@aecb35a]" name="OpenApp" is-config="true" duration-ms="12172" started-at="2018-11-13T02:51:43Z" finished-at="2018-11-13T02:51:55Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method status="FAIL" signature="TC_01_BuyProduct()[pri:0, instance:com.craftsvilla.testscripts.EmbroidedSareesScripts@aecb35a]" name="TC_01_BuyProduct" duration-ms="29579" started-at="2018-11-13T02:51:55Z" finished-at="2018-11-13T02:52:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.fail(Assert.java:103)
at com.craftsvilla.testscripts.EmbroidedSareesScripts.TC_01_BuyProduct(EmbroidedSareesScripts.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_01_BuyProduct -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.craftsvilla.testscripts.EmbroidedSareesScripts@aecb35a]" name="closeApp" is-config="true" duration-ms="1433" started-at="2018-11-13T02:52:26Z" finished-at="2018-11-13T02:52:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.craftsvilla.testscripts.EmbroidedSareesScripts -->
    </test> <!-- Regression -->
  </suite> <!-- Craftsvilla -->
</testng-results>
